// This file is auto-generated by @hey-api/openapi-ts

export const LoginDtoSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            example: 'admin@example.com',
            description: 'User email address'
        },
        password: {
            type: 'string',
            example: '12345678',
            description: 'User password',
            minLength: 8,
            maxLength: 50
        }
    },
    required: [
        'email',
        'password'
    ]
} as const;

export const TokenResponseDtoSchema = {
    type: 'object',
    properties: {
        accessToken: {
            type: 'string',
            example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
            description: 'JWT access token'
        },
        refreshToken: {
            type: 'string',
            example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
            description: 'JWT refresh token'
        }
    },
    required: [
        'accessToken',
        'refreshToken'
    ]
} as const;

export const RegisterDtoSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            example: 'user@example.com',
            description: 'User email address'
        },
        password: {
            type: 'string',
            example: 'P@ssw0rd!',
            description: 'User password',
            minLength: 8,
            maxLength: 50
        }
    },
    required: [
        'email',
        'password'
    ]
} as const;

export const MessageResponseDtoSchema = {
    type: 'object',
    properties: {
        message: {
            type: 'string',
            example: 'Operation completed successfully',
            description: 'Response message'
        }
    },
    required: [
        'message'
    ]
} as const;

export const ActiveDtoSchema = {
    type: 'object',
    properties: {
        token: {
            type: 'string',
            example: 'abc123verificationtoken',
            description: 'Email verification token'
        }
    },
    required: [
        'token'
    ]
} as const;

export const UserInformationResponseDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            example: '123e4567-e89b-12d3-a456-426614174000',
            description: 'User unique identifier'
        },
        email: {
            type: 'string',
            example: 'user@example.com',
            description: 'User email address'
        },
        fullName: {
            type: 'string',
            example: 'John Doe',
            description: 'User full name'
        }
    },
    required: [
        'id',
        'email'
    ]
} as const;

export const ForgotPasswordDtoSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            example: 'letutan500@gmail.com',
            description: 'Email address to send password reset link'
        }
    },
    required: [
        'email'
    ]
} as const;

export const ResetPasswordDtoSchema = {
    type: 'object',
    properties: {
        token: {
            type: 'string',
            example: 'abc123resettoken',
            description: 'Password reset token'
        },
        newPassword: {
            type: 'string',
            example: 'P@ssw0rd!',
            description: 'New password',
            minLength: 8,
            maxLength: 50
        }
    },
    required: [
        'token',
        'newPassword'
    ]
} as const;

export const UserListQueryDtoSchema = {
    type: 'object',
    properties: {
        page: {
            type: 'number',
            example: 1,
            default: 1
        },
        limit: {
            type: 'number',
            example: 20,
            default: 20,
            maximum: 100
        },
        email: {
            type: 'string'
        },
        role: {
            type: 'string'
        }
    }
} as const;

export const PermissionResponseDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            example: '123e4567-e89b-12d3-a456-426614174000'
        },
        module: {
            type: 'string',
            example: 'user'
        },
        action: {
            type: 'string',
            example: 'read',
            enum: [
                'create',
                'read',
                'update',
                'delete',
                'cancel',
                'publish',
                'assign.role'
            ]
        },
        description: {
            type: 'string',
            example: 'Read users permission'
        },
        isSystem: {
            type: 'boolean',
            example: false
        },
        createdAt: {
            format: 'date-time',
            type: 'string',
            example: '2024-01-01T00:00:00.000Z'
        },
        updatedAt: {
            format: 'date-time',
            type: 'string',
            example: '2024-01-01T00:00:00.000Z'
        }
    },
    required: [
        'id',
        'module',
        'action',
        'description',
        'isSystem',
        'createdAt',
        'updatedAt'
    ]
} as const;

export const RoleResponseDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            example: '123e4567-e89b-12d3-a456-426614174000',
            description: 'Role unique identifier'
        },
        name: {
            type: 'string',
            example: 'admin',
            description: 'Role name'
        },
        description: {
            type: 'string',
            example: 'Administrator role with full access',
            description: 'Role description'
        },
        createdAt: {
            format: 'date-time',
            type: 'string',
            example: '2024-01-01T00:00:00.000Z',
            description: 'Role creation date'
        },
        updatedAt: {
            format: 'date-time',
            type: 'string',
            example: '2024-01-01T00:00:00.000Z',
            description: 'Role last update date'
        },
        permissions: {
            description: 'Permissions assigned to this role',
            type: 'array',
            items: {
                $ref: '#/components/schemas/PermissionResponseDto'
            }
        }
    },
    required: [
        'id',
        'name',
        'createdAt',
        'updatedAt'
    ]
} as const;

export const UserResponseDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            example: 'c1a2b3',
            description: 'User ID'
        },
        email: {
            type: 'string',
            example: 'user@gmail.com'
        },
        fullName: {
            type: 'string',
            example: 'Tan Nguyen'
        },
        roles: {
            example: [
                {
                    id: '123e4567-e89b-12d3-a456-426614174000',
                    name: 'admin'
                }
            ],
            description: 'Roles to assign to the user',
            type: 'array',
            items: {
                $ref: '#/components/schemas/RoleResponseDto'
            }
        },
        createdAt: {
            format: 'date-time',
            type: 'string',
            example: '2026-05-03T10:00:00Z'
        },
        updatedAt: {
            format: 'date-time',
            type: 'string',
            example: '2026-05-03T10:00:00Z'
        }
    },
    required: [
        'id',
        'email',
        'fullName',
        'roles',
        'createdAt',
        'updatedAt'
    ]
} as const;

export const UserPaginatedResponseDtoSchema = {
    type: 'object',
    properties: {
        total: {
            type: 'number',
            example: 100
        },
        page: {
            type: 'number',
            example: 1
        },
        limit: {
            type: 'number',
            example: 10
        },
        data: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/UserResponseDto'
            }
        }
    },
    required: [
        'total',
        'page',
        'limit',
        'data'
    ]
} as const;

export const UserProfileDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'Name',
            description: 'Tên người dùng'
        },
        email: {
            type: 'string',
            example: 'user@example.com',
            description: 'Email người dùng'
        },
        roles: {
            example: [
                'ADMIN',
                'USER'
            ],
            description: 'Danh sách role của người dùng',
            type: 'array',
            items: {
                type: 'string'
            }
        },
        permissions: {
            example: [
                'user.read',
                'user.create',
                'post.update'
            ],
            description: 'Danh sách permission của người dùng',
            type: 'array',
            items: {
                type: 'string'
            }
        }
    },
    required: [
        'name',
        'email',
        'roles',
        'permissions'
    ]
} as const;

export const UserDetailDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            example: 'uuid-v4'
        },
        email: {
            type: 'string',
            example: 'user@example.com'
        },
        fullName: {
            type: 'string',
            example: 'Tan Nguyen',
            nullable: true
        },
        avatar: {
            type: 'string',
            example: 'https://...',
            nullable: true
        },
        roles: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/RoleResponseDto'
            }
        },
        permissions: {
            description: 'Direct permissions',
            type: 'array',
            items: {
                $ref: '#/components/schemas/PermissionResponseDto'
            }
        },
        createdAt: {
            format: 'date-time',
            type: 'string',
            example: '2026-01-01T00:00:00Z'
        },
        updatedAt: {
            format: 'date-time',
            type: 'string',
            example: '2026-01-01T00:00:00Z'
        }
    },
    required: [
        'id',
        'email',
        'fullName',
        'avatar',
        'roles',
        'permissions',
        'createdAt',
        'updatedAt'
    ]
} as const;

export const AssignRolesDtoSchema = {
    type: 'object',
    properties: {
        roleIds: {
            example: [
                '9d1c9c9e-8b7e-4f12-9f8b-123456789abc'
            ],
            description: 'Danh sách role ID',
            type: 'array',
            items: {
                type: 'string'
            }
        }
    },
    required: [
        'roleIds'
    ]
} as const;

export const AssignUserPermissionsDtoSchema = {
    type: 'object',
    properties: {
        permissionIds: {
            example: [
                '9d1c9c9e-8b7e-4f12-9f8b-123456789abc'
            ],
            description: 'Danh sách permission ID gán trực tiếp cho user',
            type: 'array',
            items: {
                type: 'string'
            }
        }
    },
    required: [
        'permissionIds'
    ]
} as const;

export const CreateRoleDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'admin',
            description: 'Role name'
        },
        description: {
            type: 'string',
            example: 'Administrator role with full access',
            description: 'Role description'
        },
        permissions: {
            example: [
                '123e4567-e89b-12d3-a456-426614174000',
                '123e4567-e89b-12d3-a456-426614174001'
            ],
            description: 'List of permission IDs for the role',
            type: 'array',
            items: {
                type: 'string'
            }
        }
    },
    required: [
        'name'
    ]
} as const;

export const RolePaginatedResponseDtoSchema = {
    type: 'object',
    properties: {
        total: {
            type: 'number',
            example: 100
        },
        page: {
            type: 'number',
            example: 1
        },
        limit: {
            type: 'number',
            example: 10
        },
        data: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/RoleResponseDto'
            }
        }
    },
    required: [
        'total',
        'page',
        'limit',
        'data'
    ]
} as const;

export const UpdateRoleDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'editor',
            description: 'Role name'
        },
        description: {
            type: 'string',
            example: 'Editor role',
            description: 'Role description'
        }
    }
} as const;

export const AssignPermissionsDtoSchema = {
    type: 'object',
    properties: {
        permissionIds: {
            example: [
                '9d1c9c9e-8b7e-4f12-9f8b-123456789abc',
                '2c7e3d1a-1234-4b6c-9a11-abcdefabcdef'
            ],
            description: 'Danh sách permission ID',
            type: 'array',
            items: {
                type: 'string'
            }
        }
    },
    required: [
        'permissionIds'
    ]
} as const;

export const CreatePermissionDtoSchema = {
    type: 'object',
    properties: {
        module: {
            type: 'string',
            example: 'user',
            description: 'Module'
        },
        action: {
            type: 'string',
            enum: [
                'create',
                'read',
                'update',
                'delete',
                'cancel',
                'publish',
                'assign.role'
            ],
            example: 'read'
        },
        description: {
            type: 'string',
            example: 'Xem danh sách người dùng'
        },
        isSystem: {
            type: 'boolean',
            example: false,
            description: 'Đánh dấu permission hệ thống'
        }
    },
    required: [
        'module',
        'action'
    ]
} as const;

export const PermissionSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            example: 'uuid-v4',
            description: 'ID permission'
        },
        module: {
            type: 'string',
            example: 'user',
            description: 'Module'
        },
        action: {
            type: 'string',
            example: 'read',
            enum: [
                'create',
                'read',
                'update',
                'delete',
                'cancel',
                'publish',
                'assign.role'
            ],
            description: 'Hành động CRUD'
        },
        description: {
            type: 'string',
            example: 'Xem danh sách người dùng'
        },
        isSystem: {
            type: 'boolean',
            example: false,
            description: 'Permission hệ thống (readonly)'
        },
        createdAt: {
            format: 'date-time',
            type: 'string',
            example: '2026-01-01T10:00:00Z'
        },
        updatedAt: {
            format: 'date-time',
            type: 'string',
            example: '2026-01-01T10:05:00Z'
        }
    },
    required: [
        'id',
        'module',
        'action',
        'isSystem',
        'createdAt',
        'updatedAt'
    ]
} as const;

export const PermissionMetaResponseDtoSchema = {
    type: 'object',
    properties: {
        modules: {
            example: [
                'user',
                'product',
                'order'
            ],
            description: 'Danh sách module hiện có',
            type: 'array',
            items: {
                type: 'string'
            }
        },
        systemActions: {
            example: [
                'read',
                'create',
                'update',
                'delete'
            ],
            description: 'Danh sách action hệ thống (CRUD)',
            type: 'array',
            items: {
                type: 'string'
            }
        },
        customActions: {
            example: [
                'approve',
                'refund'
            ],
            description: 'Danh sách action custom (non-system)',
            type: 'array',
            items: {
                type: 'string'
            }
        }
    },
    required: [
        'modules',
        'systemActions',
        'customActions'
    ]
} as const;

export const PermissionPaginatedResponseDtoSchema = {
    type: 'object',
    properties: {
        total: {
            type: 'number',
            example: 100
        },
        page: {
            type: 'number',
            example: 1
        },
        limit: {
            type: 'number',
            example: 10
        },
        data: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PermissionResponseDto'
            }
        }
    },
    required: [
        'total',
        'page',
        'limit',
        'data'
    ]
} as const;

export const UpdatePermissionDtoSchema = {
    type: 'object',
    properties: {
        description: {
            type: 'string',
            example: 'Xem & tìm kiếm người dùng'
        }
    }
} as const;

export const CreateCategoryDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'Smartphones',
            description: 'Category name'
        },
        slug: {
            type: 'string',
            example: 'smartphones',
            description: 'SEO slug (auto-generated from name if omitted)'
        },
        parent_id: {
            type: 'string',
            example: '123e4567-e89b-12d3-a456-426614174000',
            description: 'Parent category ID'
        },
        description: {
            type: 'string',
            example: 'All smartphones and mobile phones'
        },
        image: {
            type: 'string',
            example: 'https://cdn.example.com/cat.jpg'
        },
        sortOrder: {
            type: 'number',
            example: 0,
            default: 0
        },
        isActive: {
            type: 'boolean',
            example: true,
            default: true
        }
    },
    required: [
        'name'
    ]
} as const;

export const CategoryResponseDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            example: '123e4567-e89b-12d3-a456-426614174000'
        },
        parent_id: {
            type: 'object',
            example: null,
            nullable: true
        },
        name: {
            type: 'string',
            example: 'Smartphones'
        },
        slug: {
            type: 'string',
            example: 'smartphones'
        },
        description: {
            type: 'object',
            example: 'All smartphones and mobile phones',
            nullable: true
        },
        image: {
            type: 'object',
            example: 'https://cdn.example.com/cat.jpg',
            nullable: true
        },
        sortOrder: {
            type: 'number',
            example: 0
        },
        isActive: {
            type: 'boolean',
            example: true
        },
        createdAt: {
            format: 'date-time',
            type: 'string',
            example: '2026-01-01T00:00:00.000Z'
        },
        updatedAt: {
            format: 'date-time',
            type: 'string',
            example: '2026-01-01T00:00:00.000Z'
        }
    },
    required: [
        'id',
        'name',
        'slug',
        'sortOrder',
        'isActive',
        'createdAt',
        'updatedAt'
    ]
} as const;

export const CategoryPaginatedResponseDtoSchema = {
    type: 'object',
    properties: {
        total: {
            type: 'number',
            example: 100
        },
        page: {
            type: 'number',
            example: 1
        },
        limit: {
            type: 'number',
            example: 10
        },
        data: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/CategoryResponseDto'
            }
        }
    },
    required: [
        'total',
        'page',
        'limit',
        'data'
    ]
} as const;

export const CategoryTreeNodeDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            example: '123e4567-e89b-12d3-a456-426614174000'
        },
        parent_id: {
            type: 'object',
            example: null,
            nullable: true
        },
        name: {
            type: 'string',
            example: 'Smartphones'
        },
        slug: {
            type: 'string',
            example: 'smartphones'
        },
        description: {
            type: 'object',
            example: 'All smartphones and mobile phones',
            nullable: true
        },
        image: {
            type: 'object',
            example: 'https://cdn.example.com/cat.jpg',
            nullable: true
        },
        sortOrder: {
            type: 'number',
            example: 0
        },
        isActive: {
            type: 'boolean',
            example: true
        },
        createdAt: {
            format: 'date-time',
            type: 'string',
            example: '2026-01-01T00:00:00.000Z'
        },
        updatedAt: {
            format: 'date-time',
            type: 'string',
            example: '2026-01-01T00:00:00.000Z'
        },
        children: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/CategoryTreeNodeDto'
            }
        }
    },
    required: [
        'id',
        'name',
        'slug',
        'sortOrder',
        'isActive',
        'createdAt',
        'updatedAt'
    ]
} as const;

export const UpdateCategoryDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'Smartphones',
            description: 'Category name'
        },
        slug: {
            type: 'string',
            example: 'smartphones',
            description: 'SEO slug (auto-generated from name if omitted)'
        },
        parent_id: {
            type: 'string',
            example: '123e4567-e89b-12d3-a456-426614174000',
            description: 'Parent category ID'
        },
        description: {
            type: 'string',
            example: 'All smartphones and mobile phones'
        },
        image: {
            type: 'string',
            example: 'https://cdn.example.com/cat.jpg'
        },
        sortOrder: {
            type: 'number',
            example: 0,
            default: 0
        },
        isActive: {
            type: 'boolean',
            example: true,
            default: true
        }
    }
} as const;

export const CreateProductImageDtoSchema = {
    type: 'object',
    properties: {
        url: {
            type: 'string',
            example: 'https://cdn.example.com/img.jpg'
        },
        alt: {
            type: 'string',
            example: 'Product front view'
        },
        isPrimary: {
            type: 'boolean',
            example: false,
            default: false
        },
        sortOrder: {
            type: 'number',
            example: 0,
            default: 0
        }
    },
    required: [
        'url'
    ]
} as const;

export const CreateProductVariantDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'Đỏ - L'
        },
        sku: {
            type: 'string',
            example: 'PROD-001-RED-L'
        },
        price: {
            type: 'number',
            example: 299000
        },
        stock: {
            type: 'number',
            example: 100,
            default: 0
        },
        attributes: {
            type: 'object',
            example: {
                color: 'red',
                size: 'L'
            }
        },
        isActive: {
            type: 'boolean',
            example: true,
            default: true
        }
    },
    required: [
        'name',
        'sku',
        'price'
    ]
} as const;

export const CreateProductDtoSchema = {
    type: 'object',
    properties: {
        category_id: {
            type: 'string',
            example: 'uuid-v4'
        },
        name: {
            type: 'string',
            example: 'iPhone 15 Pro'
        },
        slug: {
            type: 'string',
            example: 'iphone-15-pro',
            description: 'Auto-generated from name if omitted'
        },
        description: {
            type: 'string'
        },
        basePrice: {
            type: 'number',
            example: 29990000
        },
        sku: {
            type: 'string',
            example: 'IPH-15-PRO'
        },
        status: {
            type: 'string',
            enum: [
                'draft',
                'published',
                'archived'
            ],
            default: 'draft'
        },
        isFeatured: {
            type: 'boolean',
            example: false,
            default: false
        },
        images: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/CreateProductImageDto'
            }
        },
        variants: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/CreateProductVariantDto'
            }
        },
        tagIds: {
            example: [
                'uuid-tag-1',
                'uuid-tag-2'
            ],
            type: 'array',
            items: {
                type: 'string'
            }
        }
    },
    required: [
        'category_id',
        'name',
        'basePrice',
        'sku'
    ]
} as const;

export const ProductImageResponseDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        url: {
            type: 'string'
        },
        alt: {
            type: 'object',
            nullable: true
        },
        isPrimary: {
            type: 'boolean'
        },
        sortOrder: {
            type: 'number'
        }
    },
    required: [
        'id',
        'url',
        'isPrimary',
        'sortOrder'
    ]
} as const;

export const ProductVariantResponseDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        sku: {
            type: 'string'
        },
        price: {
            type: 'number'
        },
        stock: {
            type: 'number'
        },
        attributes: {
            type: 'object',
            nullable: true
        },
        isActive: {
            type: 'boolean'
        },
        createdAt: {
            format: 'date-time',
            type: 'string'
        },
        updatedAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: [
        'id',
        'name',
        'sku',
        'price',
        'stock',
        'isActive',
        'createdAt',
        'updatedAt'
    ]
} as const;

export const TagResponseDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        slug: {
            type: 'string'
        }
    },
    required: [
        'id',
        'name',
        'slug'
    ]
} as const;

export const ProductResponseDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        category_id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        slug: {
            type: 'string'
        },
        description: {
            type: 'object',
            nullable: true
        },
        basePrice: {
            type: 'number'
        },
        sku: {
            type: 'string'
        },
        status: {
            type: 'string',
            enum: [
                'draft',
                'published',
                'archived'
            ]
        },
        isFeatured: {
            type: 'boolean'
        },
        images: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/ProductImageResponseDto'
            }
        },
        variants: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/ProductVariantResponseDto'
            }
        },
        tags: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/TagResponseDto'
            }
        },
        createdAt: {
            format: 'date-time',
            type: 'string'
        },
        updatedAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: [
        'id',
        'category_id',
        'name',
        'slug',
        'basePrice',
        'sku',
        'status',
        'isFeatured',
        'images',
        'variants',
        'tags',
        'createdAt',
        'updatedAt'
    ]
} as const;

export const ProductListItemDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        category_id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        slug: {
            type: 'string'
        },
        basePrice: {
            type: 'number'
        },
        sku: {
            type: 'string'
        },
        status: {
            type: 'string',
            enum: [
                'draft',
                'published',
                'archived'
            ]
        },
        isFeatured: {
            type: 'boolean'
        },
        createdAt: {
            format: 'date-time',
            type: 'string'
        },
        updatedAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: [
        'id',
        'category_id',
        'name',
        'slug',
        'basePrice',
        'sku',
        'status',
        'isFeatured',
        'createdAt',
        'updatedAt'
    ]
} as const;

export const ProductPaginatedResponseDtoSchema = {
    type: 'object',
    properties: {
        total: {
            type: 'number',
            example: 100
        },
        page: {
            type: 'number',
            example: 1
        },
        limit: {
            type: 'number',
            example: 10
        },
        data: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/ProductListItemDto'
            }
        }
    },
    required: [
        'total',
        'page',
        'limit',
        'data'
    ]
} as const;

export const UpdateProductDtoSchema = {
    type: 'object',
    properties: {
        category_id: {
            type: 'string',
            example: 'uuid-v4'
        },
        name: {
            type: 'string',
            example: 'iPhone 15 Pro'
        },
        slug: {
            type: 'string',
            example: 'iphone-15-pro',
            description: 'Auto-generated from name if omitted'
        },
        description: {
            type: 'string'
        },
        basePrice: {
            type: 'number',
            example: 29990000
        },
        sku: {
            type: 'string',
            example: 'IPH-15-PRO'
        },
        status: {
            type: 'string',
            enum: [
                'draft',
                'published',
                'archived'
            ],
            default: 'draft'
        },
        isFeatured: {
            type: 'boolean',
            example: false,
            default: false
        },
        images: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/CreateProductImageDto'
            }
        },
        variants: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/CreateProductVariantDto'
            }
        },
        tagIds: {
            example: [
                'uuid-tag-1',
                'uuid-tag-2'
            ],
            type: 'array',
            items: {
                type: 'string'
            }
        }
    }
} as const;

export const UpdateProductVariantDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'Đỏ - L'
        },
        sku: {
            type: 'string',
            example: 'PROD-001-RED-L'
        },
        price: {
            type: 'number',
            example: 299000
        },
        stock: {
            type: 'number',
            example: 100,
            default: 0
        },
        attributes: {
            type: 'object',
            example: {
                color: 'red',
                size: 'L'
            }
        },
        isActive: {
            type: 'boolean',
            example: true,
            default: true
        }
    }
} as const;

export const CreateTagDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'sale'
        },
        slug: {
            type: 'string',
            example: 'sale',
            description: 'Auto-generated from name if omitted'
        }
    },
    required: [
        'name'
    ]
} as const;

export const AddressResponseDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        fullName: {
            type: 'string'
        },
        phone: {
            type: 'string'
        },
        addressLine1: {
            type: 'string'
        },
        addressLine2: {
            type: 'object'
        },
        city: {
            type: 'string'
        },
        province: {
            type: 'string'
        },
        country: {
            type: 'string'
        },
        postalCode: {
            type: 'object'
        },
        isDefault: {
            type: 'boolean'
        },
        createdAt: {
            format: 'date-time',
            type: 'string'
        },
        updatedAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: [
        'id',
        'fullName',
        'phone',
        'addressLine1',
        'city',
        'province',
        'country',
        'isDefault',
        'createdAt',
        'updatedAt'
    ]
} as const;

export const CreateAddressDtoSchema = {
    type: 'object',
    properties: {
        fullName: {
            type: 'string',
            example: 'Nguyễn Văn A'
        },
        phone: {
            type: 'string',
            example: '0901234567'
        },
        addressLine1: {
            type: 'string',
            example: '123 Đường Lê Lợi'
        },
        addressLine2: {
            type: 'string',
            example: 'Phường Bến Nghé'
        },
        city: {
            type: 'string',
            example: 'Thành phố Hồ Chí Minh'
        },
        province: {
            type: 'string',
            example: 'Hồ Chí Minh'
        },
        country: {
            type: 'string',
            example: 'VN',
            default: 'VN'
        },
        postalCode: {
            type: 'string',
            example: '700000'
        },
        isDefault: {
            type: 'boolean',
            example: false,
            default: false
        }
    },
    required: [
        'fullName',
        'phone',
        'addressLine1',
        'city',
        'province'
    ]
} as const;

export const UpdateAddressDtoSchema = {
    type: 'object',
    properties: {
        fullName: {
            type: 'string',
            example: 'Nguyễn Văn A'
        },
        phone: {
            type: 'string',
            example: '0901234567'
        },
        addressLine1: {
            type: 'string',
            example: '123 Đường Lê Lợi'
        },
        addressLine2: {
            type: 'string',
            example: 'Phường Bến Nghé'
        },
        city: {
            type: 'string',
            example: 'Thành phố Hồ Chí Minh'
        },
        province: {
            type: 'string',
            example: 'Hồ Chí Minh'
        },
        country: {
            type: 'string',
            example: 'VN',
            default: 'VN'
        },
        postalCode: {
            type: 'string',
            example: '700000'
        },
        isDefault: {
            type: 'boolean',
            example: false,
            default: false
        }
    }
} as const;

export const CreateOrderItemDtoSchema = {
    type: 'object',
    properties: {
        variant_id: {
            type: 'string',
            example: 'uuid-v4',
            description: 'Product variant ID'
        },
        quantity: {
            type: 'number',
            example: 2
        }
    },
    required: [
        'variant_id',
        'quantity'
    ]
} as const;

export const CreateOrderDtoSchema = {
    type: 'object',
    properties: {
        address_id: {
            type: 'string',
            example: 'uuid-v4',
            description: 'Delivery address ID'
        },
        items: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/CreateOrderItemDto'
            }
        },
        discountCode: {
            type: 'string',
            example: 'SALE20',
            description: 'Discount coupon code'
        },
        notes: {
            type: 'string',
            example: 'Giao giờ hành chính'
        }
    },
    required: [
        'address_id',
        'items'
    ]
} as const;

export const OrderItemResponseDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        order_id: {
            type: 'string'
        },
        variant_id: {
            type: 'object'
        },
        productName: {
            type: 'string'
        },
        variantName: {
            type: 'object'
        },
        unitPrice: {
            type: 'number'
        },
        quantity: {
            type: 'number'
        },
        total: {
            type: 'number'
        }
    },
    required: [
        'id',
        'order_id',
        'productName',
        'unitPrice',
        'quantity',
        'total'
    ]
} as const;

export const AppliedDiscountDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        code: {
            type: 'string'
        },
        type: {
            type: 'string',
            enum: [
                'percent',
                'fixed'
            ]
        },
        value: {
            type: 'number'
        }
    },
    required: [
        'id',
        'code',
        'type',
        'value'
    ]
} as const;

export const OrderResponseDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        user_id: {
            type: 'string'
        },
        address_id: {
            type: 'object'
        },
        orderNumber: {
            type: 'string'
        },
        status: {
            type: 'string',
            enum: [
                'pending',
                'confirmed',
                'processing',
                'shipped',
                'delivered',
                'cancelled',
                'refunded'
            ]
        },
        subtotal: {
            type: 'number'
        },
        shippingFee: {
            type: 'number'
        },
        discount: {
            type: 'number'
        },
        total: {
            type: 'number'
        },
        notes: {
            type: 'object'
        },
        items: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/OrderItemResponseDto'
            }
        },
        discounts: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/AppliedDiscountDto'
            }
        },
        createdAt: {
            format: 'date-time',
            type: 'string'
        },
        updatedAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: [
        'id',
        'user_id',
        'orderNumber',
        'status',
        'subtotal',
        'shippingFee',
        'discount',
        'total',
        'items',
        'discounts',
        'createdAt',
        'updatedAt'
    ]
} as const;

export const OrderListItemDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        user_id: {
            type: 'string'
        },
        orderNumber: {
            type: 'string'
        },
        status: {
            type: 'string',
            enum: [
                'pending',
                'confirmed',
                'processing',
                'shipped',
                'delivered',
                'cancelled',
                'refunded'
            ]
        },
        total: {
            type: 'number'
        },
        createdAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: [
        'id',
        'user_id',
        'orderNumber',
        'status',
        'total',
        'createdAt'
    ]
} as const;

export const OrderPaginatedResponseDtoSchema = {
    type: 'object',
    properties: {
        total: {
            type: 'number',
            example: 100
        },
        page: {
            type: 'number',
            example: 1
        },
        limit: {
            type: 'number',
            example: 10
        },
        data: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/OrderListItemDto'
            }
        }
    },
    required: [
        'total',
        'page',
        'limit',
        'data'
    ]
} as const;

export const UpdateOrderStatusDtoSchema = {
    type: 'object',
    properties: {
        status: {
            type: 'string',
            enum: [
                'pending',
                'confirmed',
                'processing',
                'shipped',
                'delivered',
                'cancelled',
                'refunded'
            ]
        }
    },
    required: [
        'status'
    ]
} as const;

export const ValidateDiscountDtoSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'string',
            example: 'SALE20'
        },
        subtotal: {
            type: 'number',
            example: 500000,
            description: 'Order subtotal to calculate discount against'
        }
    },
    required: [
        'code',
        'subtotal'
    ]
} as const;

export const ValidateDiscountResponseDtoSchema = {
    type: 'object',
    properties: {
        discountId: {
            type: 'string'
        },
        code: {
            type: 'string'
        },
        type: {
            type: 'string',
            enum: [
                'percent',
                'fixed'
            ]
        },
        value: {
            type: 'number'
        },
        discountAmount: {
            type: 'number',
            description: 'Computed discount amount in VND'
        }
    },
    required: [
        'discountId',
        'code',
        'type',
        'value',
        'discountAmount'
    ]
} as const;

export const CreateDiscountDtoSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'string',
            example: 'SALE20'
        },
        type: {
            type: 'string',
            enum: [
                'percent',
                'fixed'
            ],
            example: 'percent'
        },
        value: {
            type: 'number',
            example: 20,
            description: 'Percent (0–100) or fixed amount in VND'
        },
        minOrderValue: {
            type: 'number',
            example: 100000,
            description: 'Minimum subtotal to apply'
        },
        usageLimit: {
            type: 'number',
            example: 100,
            description: 'Max total usages (null = unlimited)'
        },
        isActive: {
            type: 'boolean',
            example: true
        },
        startsAt: {
            format: 'date-time',
            type: 'string',
            example: '2026-01-01T00:00:00Z'
        },
        expiresAt: {
            format: 'date-time',
            type: 'string',
            example: '2026-12-31T23:59:59Z'
        }
    },
    required: [
        'code',
        'type',
        'value'
    ]
} as const;

export const DiscountResponseDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        code: {
            type: 'string'
        },
        type: {
            type: 'string',
            enum: [
                'percent',
                'fixed'
            ]
        },
        value: {
            type: 'number'
        },
        minOrderValue: {
            type: 'object'
        },
        usageLimit: {
            type: 'object'
        },
        usedCount: {
            type: 'number'
        },
        isActive: {
            type: 'boolean'
        },
        startsAt: {
            type: 'object'
        },
        expiresAt: {
            type: 'object'
        },
        createdAt: {
            format: 'date-time',
            type: 'string'
        },
        updatedAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: [
        'id',
        'code',
        'type',
        'value',
        'usedCount',
        'isActive',
        'createdAt',
        'updatedAt'
    ]
} as const;

export const DiscountPaginatedResponseDtoSchema = {
    type: 'object',
    properties: {
        total: {
            type: 'number',
            example: 100
        },
        page: {
            type: 'number',
            example: 1
        },
        limit: {
            type: 'number',
            example: 10
        },
        data: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/DiscountResponseDto'
            }
        }
    },
    required: [
        'total',
        'page',
        'limit',
        'data'
    ]
} as const;

export const UpdateDiscountDtoSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'string',
            example: 'SALE20'
        },
        type: {
            type: 'string',
            enum: [
                'percent',
                'fixed'
            ],
            example: 'percent'
        },
        value: {
            type: 'number',
            example: 20,
            description: 'Percent (0–100) or fixed amount in VND'
        },
        minOrderValue: {
            type: 'number',
            example: 100000,
            description: 'Minimum subtotal to apply'
        },
        usageLimit: {
            type: 'number',
            example: 100,
            description: 'Max total usages (null = unlimited)'
        },
        isActive: {
            type: 'boolean',
            example: true
        },
        startsAt: {
            format: 'date-time',
            type: 'string',
            example: '2026-01-01T00:00:00Z'
        },
        expiresAt: {
            format: 'date-time',
            type: 'string',
            example: '2026-12-31T23:59:59Z'
        }
    }
} as const;

export const CreatePaymentDtoSchema = {
    type: 'object',
    properties: {
        order_id: {
            type: 'string',
            example: 'uuid-v4',
            description: 'Order ID to pay for'
        },
        method: {
            type: 'string',
            enum: [
                'cod',
                'vnpay',
                'momo',
                'zalopay',
                'stripe',
                'bank_transfer'
            ],
            example: 'cod'
        }
    },
    required: [
        'order_id',
        'method'
    ]
} as const;

export const PaymentResponseDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        order_id: {
            type: 'string'
        },
        method: {
            type: 'string',
            enum: [
                'cod',
                'vnpay',
                'momo',
                'zalopay',
                'stripe',
                'bank_transfer'
            ]
        },
        status: {
            type: 'string',
            enum: [
                'pending',
                'completed',
                'failed',
                'refunded'
            ]
        },
        amount: {
            type: 'number'
        },
        transactionId: {
            type: 'object'
        },
        metadata: {
            type: 'object'
        },
        paidAt: {
            type: 'object'
        },
        createdAt: {
            format: 'date-time',
            type: 'string'
        },
        updatedAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: [
        'id',
        'order_id',
        'method',
        'status',
        'amount',
        'createdAt',
        'updatedAt'
    ]
} as const;

export const PaymentPaginatedResponseDtoSchema = {
    type: 'object',
    properties: {
        total: {
            type: 'number',
            example: 100
        },
        page: {
            type: 'number',
            example: 1
        },
        limit: {
            type: 'number',
            example: 10
        },
        data: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PaymentResponseDto'
            }
        }
    },
    required: [
        'total',
        'page',
        'limit',
        'data'
    ]
} as const;

export const UpdatePaymentStatusDtoSchema = {
    type: 'object',
    properties: {
        status: {
            type: 'string',
            enum: [
                'pending',
                'completed',
                'failed',
                'refunded'
            ]
        },
        transactionId: {
            type: 'string',
            example: 'TXN-ABC123'
        },
        metadata: {
            type: 'object',
            description: 'Raw response from payment gateway'
        }
    },
    required: [
        'status'
    ]
} as const;

export const CartItemVariantDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        sku: {
            type: 'string'
        },
        price: {
            type: 'number'
        },
        stock: {
            type: 'number'
        },
        attributes: {
            type: 'object'
        }
    },
    required: [
        'id',
        'name',
        'sku',
        'price',
        'stock'
    ]
} as const;

export const CartItemResponseDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        cart_id: {
            type: 'string'
        },
        variant_id: {
            type: 'string'
        },
        variant: {
            $ref: '#/components/schemas/CartItemVariantDto'
        },
        quantity: {
            type: 'number'
        },
        createdAt: {
            format: 'date-time',
            type: 'string'
        },
        updatedAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: [
        'id',
        'cart_id',
        'variant_id',
        'variant',
        'quantity',
        'createdAt',
        'updatedAt'
    ]
} as const;

export const CartResponseDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        user_id: {
            type: 'string'
        },
        items: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/CartItemResponseDto'
            }
        },
        createdAt: {
            format: 'date-time',
            type: 'string'
        },
        updatedAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: [
        'id',
        'user_id',
        'items',
        'createdAt',
        'updatedAt'
    ]
} as const;

export const AddCartItemDtoSchema = {
    type: 'object',
    properties: {
        variant_id: {
            type: 'string',
            example: 'uuid-v4'
        },
        quantity: {
            type: 'number',
            example: 1,
            default: 1
        }
    },
    required: [
        'variant_id'
    ]
} as const;

export const UpdateCartItemDtoSchema = {
    type: 'object',
    properties: {
        quantity: {
            type: 'number',
            example: 2,
            description: 'New quantity (min 1)'
        }
    },
    required: [
        'quantity'
    ]
} as const;

export const CreateReviewDtoSchema = {
    type: 'object',
    properties: {
        product_id: {
            type: 'string',
            description: 'Product to review'
        },
        rating: {
            type: 'number',
            minimum: 1,
            maximum: 5
        },
        title: {
            type: 'string',
            maxLength: 255
        },
        content: {
            type: 'string'
        }
    },
    required: [
        'product_id',
        'rating'
    ]
} as const;

export const ReviewAuthorDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        fullName: {
            type: 'object',
            nullable: true
        },
        avatar: {
            type: 'object',
            nullable: true
        }
    },
    required: [
        'id'
    ]
} as const;

export const ReviewResponseDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        user_id: {
            type: 'string'
        },
        user: {
            $ref: '#/components/schemas/ReviewAuthorDto'
        },
        product_id: {
            type: 'string'
        },
        rating: {
            type: 'number'
        },
        title: {
            type: 'object',
            nullable: true
        },
        content: {
            type: 'object',
            nullable: true
        },
        isVerified: {
            type: 'boolean'
        },
        isApproved: {
            type: 'boolean'
        },
        createdAt: {
            format: 'date-time',
            type: 'string'
        },
        updatedAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: [
        'id',
        'user_id',
        'user',
        'product_id',
        'rating',
        'isVerified',
        'isApproved',
        'createdAt',
        'updatedAt'
    ]
} as const;

export const ReviewPaginatedResponseDtoSchema = {
    type: 'object',
    properties: {
        total: {
            type: 'number',
            example: 100
        },
        page: {
            type: 'number',
            example: 1
        },
        limit: {
            type: 'number',
            example: 10
        },
        data: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/ReviewResponseDto'
            }
        }
    },
    required: [
        'total',
        'page',
        'limit',
        'data'
    ]
} as const;

export const UpdateReviewDtoSchema = {
    type: 'object',
    properties: {
        rating: {
            type: 'number',
            minimum: 1,
            maximum: 5
        },
        title: {
            type: 'string',
            maxLength: 255
        },
        content: {
            type: 'string'
        }
    }
} as const;

export const WishlistProductDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        slug: {
            type: 'string'
        },
        basePrice: {
            type: 'number'
        },
        sku: {
            type: 'string'
        },
        status: {
            type: 'string',
            enum: [
                'draft',
                'published',
                'archived'
            ]
        },
        isFeatured: {
            type: 'boolean'
        },
        description: {
            type: 'object',
            nullable: true
        }
    },
    required: [
        'id',
        'name',
        'slug',
        'basePrice',
        'sku',
        'status',
        'isFeatured'
    ]
} as const;

export const WishlistItemResponseDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        product_id: {
            type: 'string'
        },
        product: {
            $ref: '#/components/schemas/WishlistProductDto'
        },
        createdAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: [
        'id',
        'product_id',
        'product',
        'createdAt'
    ]
} as const;

export const WishlistResponseDtoSchema = {
    type: 'object',
    properties: {
        items: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/WishlistItemResponseDto'
            }
        },
        total: {
            type: 'number'
        }
    },
    required: [
        'items',
        'total'
    ]
} as const;

export const AddToWishlistDtoSchema = {
    type: 'object',
    properties: {
        product_id: {
            type: 'string',
            example: 'uuid-v4',
            description: 'Product ID to add'
        }
    },
    required: [
        'product_id'
    ]
} as const;
