// This file is auto-generated by @hey-api/openapi-ts

import type { AddressesControllerCreateResponse, AddressesControllerFindAllResponse, AddressesControllerFindOneResponse, AddressesControllerSetDefaultResponse, AddressesControllerUpdateResponse, BannersControllerFindActiveResponse, CartsControllerAddItemResponse, CartsControllerGetCartResponse, CartsControllerRemoveItemResponse, CartsControllerUpdateItemResponse, CategoriesControllerFindAllResponse, CategoriesControllerFindBySlugResponse, CategoriesControllerFindOneResponse, CategoriesControllerFindTreeResponse, OrdersControllerCancelResponse, OrdersControllerCheckoutResponse, OrdersControllerCreateResponse, OrdersControllerFindMineOneResponse, OrdersControllerFindMineResponse, OrdersControllerGetHistoryResponse, OrdersControllerUpdateResponse, PaymentsControllerCreateResponse, PaymentsControllerFindMineOneResponse, PaymentsControllerFindMineResponse, ProductReviewsControllerFindApprovedResponse, ProductsControllerFindAllResponse, ProductsControllerFindBySlugResponse, ProductsControllerFindOneResponse, ReviewsControllerCreateResponse, ReviewsControllerFindMyReviewsResponse, ReviewsControllerUpdateResponse, WishlistsControllerAddProductResponse, WishlistsControllerGetWishlistResponse, WishlistsControllerRemoveProductResponse } from './types.gen';

const categoryResponseDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

const categoryPaginatedResponseDtoSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => categoryResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const categoriesControllerFindAllResponseTransformer = async (data: any): Promise<CategoriesControllerFindAllResponse> => {
    data = categoryPaginatedResponseDtoSchemaResponseTransformer(data);
    return data;
};

const categoryTreeNodeDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    if (data.children) {
        data.children = data.children.map((item: any) => categoryTreeNodeDtoSchemaResponseTransformer(item));
    }
    return data;
};

export const categoriesControllerFindTreeResponseTransformer = async (data: any): Promise<CategoriesControllerFindTreeResponse> => {
    data = data.map((item: any) => categoryTreeNodeDtoSchemaResponseTransformer(item));
    return data;
};

export const categoriesControllerFindBySlugResponseTransformer = async (data: any): Promise<CategoriesControllerFindBySlugResponse> => {
    data = categoryResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const categoriesControllerFindOneResponseTransformer = async (data: any): Promise<CategoriesControllerFindOneResponse> => {
    data = categoryResponseDtoSchemaResponseTransformer(data);
    return data;
};

const productListItemDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

const productPaginatedResponseDtoSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => productListItemDtoSchemaResponseTransformer(item));
    return data;
};

export const productsControllerFindAllResponseTransformer = async (data: any): Promise<ProductsControllerFindAllResponse> => {
    data = productPaginatedResponseDtoSchemaResponseTransformer(data);
    return data;
};

const productVariantResponseDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

const productResponseDtoSchemaResponseTransformer = (data: any) => {
    data.variants = data.variants.map((item: any) => productVariantResponseDtoSchemaResponseTransformer(item));
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const productsControllerFindBySlugResponseTransformer = async (data: any): Promise<ProductsControllerFindBySlugResponse> => {
    data = productResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const productsControllerFindOneResponseTransformer = async (data: any): Promise<ProductsControllerFindOneResponse> => {
    data = productResponseDtoSchemaResponseTransformer(data);
    return data;
};

const addressResponseDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const addressesControllerFindAllResponseTransformer = async (data: any): Promise<AddressesControllerFindAllResponse> => {
    data = data.map((item: any) => addressResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const addressesControllerCreateResponseTransformer = async (data: any): Promise<AddressesControllerCreateResponse> => {
    data = addressResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const addressesControllerFindOneResponseTransformer = async (data: any): Promise<AddressesControllerFindOneResponse> => {
    data = addressResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const addressesControllerUpdateResponseTransformer = async (data: any): Promise<AddressesControllerUpdateResponse> => {
    data = addressResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const addressesControllerSetDefaultResponseTransformer = async (data: any): Promise<AddressesControllerSetDefaultResponse> => {
    data = addressResponseDtoSchemaResponseTransformer(data);
    return data;
};

const orderResponseDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const ordersControllerCreateResponseTransformer = async (data: any): Promise<OrdersControllerCreateResponse> => {
    data = orderResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const ordersControllerCheckoutResponseTransformer = async (data: any): Promise<OrdersControllerCheckoutResponse> => {
    data = orderResponseDtoSchemaResponseTransformer(data);
    return data;
};

const orderListItemDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

const orderPaginatedResponseDtoSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => orderListItemDtoSchemaResponseTransformer(item));
    return data;
};

export const ordersControllerFindMineResponseTransformer = async (data: any): Promise<OrdersControllerFindMineResponse> => {
    data = orderPaginatedResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const ordersControllerFindMineOneResponseTransformer = async (data: any): Promise<OrdersControllerFindMineOneResponse> => {
    data = orderResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const ordersControllerUpdateResponseTransformer = async (data: any): Promise<OrdersControllerUpdateResponse> => {
    data = orderResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const ordersControllerCancelResponseTransformer = async (data: any): Promise<OrdersControllerCancelResponse> => {
    data = orderResponseDtoSchemaResponseTransformer(data);
    return data;
};

const orderStatusHistoryResponseDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

export const ordersControllerGetHistoryResponseTransformer = async (data: any): Promise<OrdersControllerGetHistoryResponse> => {
    data = data.map((item: any) => orderStatusHistoryResponseDtoSchemaResponseTransformer(item));
    return data;
};

const cartItemResponseDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

const cartResponseDtoSchemaResponseTransformer = (data: any) => {
    data.items = data.items.map((item: any) => cartItemResponseDtoSchemaResponseTransformer(item));
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const cartsControllerGetCartResponseTransformer = async (data: any): Promise<CartsControllerGetCartResponse> => {
    data = cartResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const cartsControllerAddItemResponseTransformer = async (data: any): Promise<CartsControllerAddItemResponse> => {
    data = cartResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const cartsControllerRemoveItemResponseTransformer = async (data: any): Promise<CartsControllerRemoveItemResponse> => {
    data = cartResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const cartsControllerUpdateItemResponseTransformer = async (data: any): Promise<CartsControllerUpdateItemResponse> => {
    data = cartResponseDtoSchemaResponseTransformer(data);
    return data;
};

const paymentResponseDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const paymentsControllerCreateResponseTransformer = async (data: any): Promise<PaymentsControllerCreateResponse> => {
    data = paymentResponseDtoSchemaResponseTransformer(data);
    return data;
};

const paymentPaginatedResponseDtoSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => paymentResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const paymentsControllerFindMineResponseTransformer = async (data: any): Promise<PaymentsControllerFindMineResponse> => {
    data = paymentPaginatedResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const paymentsControllerFindMineOneResponseTransformer = async (data: any): Promise<PaymentsControllerFindMineOneResponse> => {
    data = paymentResponseDtoSchemaResponseTransformer(data);
    return data;
};

const reviewResponseDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const reviewsControllerCreateResponseTransformer = async (data: any): Promise<ReviewsControllerCreateResponse> => {
    data = reviewResponseDtoSchemaResponseTransformer(data);
    return data;
};

const reviewPaginatedResponseDtoSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => reviewResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const reviewsControllerFindMyReviewsResponseTransformer = async (data: any): Promise<ReviewsControllerFindMyReviewsResponse> => {
    data = reviewPaginatedResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const reviewsControllerUpdateResponseTransformer = async (data: any): Promise<ReviewsControllerUpdateResponse> => {
    data = reviewResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const productReviewsControllerFindApprovedResponseTransformer = async (data: any): Promise<ProductReviewsControllerFindApprovedResponse> => {
    data = reviewPaginatedResponseDtoSchemaResponseTransformer(data);
    return data;
};

const wishlistItemResponseDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

const wishlistResponseDtoSchemaResponseTransformer = (data: any) => {
    data.items = data.items.map((item: any) => wishlistItemResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const wishlistsControllerGetWishlistResponseTransformer = async (data: any): Promise<WishlistsControllerGetWishlistResponse> => {
    data = wishlistResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const wishlistsControllerAddProductResponseTransformer = async (data: any): Promise<WishlistsControllerAddProductResponse> => {
    data = wishlistResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const wishlistsControllerRemoveProductResponseTransformer = async (data: any): Promise<WishlistsControllerRemoveProductResponse> => {
    data = wishlistResponseDtoSchemaResponseTransformer(data);
    return data;
};

const bannerResponseDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const bannersControllerFindActiveResponseTransformer = async (data: any): Promise<BannersControllerFindActiveResponse> => {
    data = data.map((item: any) => bannerResponseDtoSchemaResponseTransformer(item));
    return data;
};
