// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type LoginDto = {
    /**
     * User email address
     */
    email: string;
    /**
     * User password
     */
    password: string;
};

export type TokenResponseDto = {
    /**
     * JWT access token
     */
    accessToken: string;
    /**
     * JWT refresh token
     */
    refreshToken: string;
};

export type RegisterDto = {
    /**
     * User email address
     */
    email: string;
    /**
     * User password
     */
    password: string;
};

export type MessageResponseDto = {
    /**
     * Response message
     */
    message: string;
};

export type ActiveDto = {
    /**
     * Email verification token
     */
    token: string;
};

export type UserInformationResponseDto = {
    /**
     * User unique identifier
     */
    id: string;
    /**
     * User email address
     */
    email: string;
    /**
     * User full name
     */
    fullName?: string;
};

export type ForgotPasswordDto = {
    /**
     * Email address to send password reset link
     */
    email: string;
};

export type ResetPasswordDto = {
    /**
     * Password reset token
     */
    token: string;
    /**
     * New password
     */
    newPassword: string;
};

export type UserProfileDto = {
    /**
     * ID người dùng
     */
    id: string;
    /**
     * Tên người dùng
     */
    name: string;
    /**
     * Email người dùng
     */
    email: string;
    /**
     * Danh sách role của người dùng
     */
    roles: Array<string>;
    /**
     * Danh sách permission của người dùng
     */
    permissions: Array<string>;
};

export type UserListQueryDto = {
    page?: number;
    limit?: number;
    email?: string;
    role?: string;
    userCode?: string;
};

export type PermissionResponseDto = {
    id: string;
    module: string;
    action: 'create' | 'read' | 'update' | 'delete' | 'cancel' | 'publish' | 'upload' | 'assign.role';
    description: string;
    isSystem: boolean;
    createdAt: Date;
    updatedAt: Date;
};

export type RoleResponseDto = {
    /**
     * Role unique identifier
     */
    id: string;
    /**
     * Role name
     */
    name: string;
    /**
     * Role description
     */
    description?: string;
    /**
     * Role creation date
     */
    createdAt: Date;
    /**
     * Role last update date
     */
    updatedAt: Date;
    /**
     * Permissions assigned to this role
     */
    permissions?: Array<PermissionResponseDto>;
};

export type UserResponseDto = {
    /**
     * User ID
     */
    id: string;
    userCode: string;
    email: string;
    fullName: string;
    /**
     * Roles to assign to the user
     */
    roles: Array<RoleResponseDto>;
    createdAt: Date;
    updatedAt: Date;
};

export type UserPaginatedResponseDto = {
    total: number;
    page: number;
    limit: number;
    data: Array<UserResponseDto>;
};

export type UserDetailDto = {
    id: string;
    userCode: string;
    email: string;
    fullName: string | null;
    avatar: string | null;
    roles: Array<RoleResponseDto>;
    /**
     * Direct permissions
     */
    permissions: Array<PermissionResponseDto>;
    createdAt: Date;
    updatedAt: Date;
};

export type AssignRolesDto = {
    /**
     * Danh sách role ID
     */
    roleIds: Array<string>;
};

export type AssignUserPermissionsDto = {
    /**
     * Danh sách permission ID gán trực tiếp cho user
     */
    permissionIds: Array<string>;
};

export type CreateRoleDto = {
    /**
     * Role name
     */
    name: string;
    /**
     * Role description
     */
    description?: string;
    /**
     * List of permission IDs for the role
     */
    permissions?: Array<string>;
};

export type RolePaginatedResponseDto = {
    total: number;
    page: number;
    limit: number;
    data: Array<RoleResponseDto>;
};

export type UpdateRoleDto = {
    /**
     * Role name
     */
    name?: string;
    /**
     * Role description
     */
    description?: string;
};

export type AssignPermissionsDto = {
    /**
     * Danh sách permission ID
     */
    permissionIds: Array<string>;
};

export type CreatePermissionDto = {
    /**
     * Module
     */
    module: string;
    action: 'create' | 'read' | 'update' | 'delete' | 'cancel' | 'publish' | 'upload' | 'assign.role';
    description?: string;
    /**
     * Đánh dấu permission hệ thống
     */
    isSystem?: boolean;
};

export type Permission = {
    /**
     * ID
     */
    id: string;
    /**
     * Thời gian tạo
     */
    createdAt: Date;
    /**
     * Thời gian cập nhật
     */
    updatedAt: Date;
    /**
     * Module
     */
    module: string;
    /**
     * Hành động CRUD
     */
    action: 'create' | 'read' | 'update' | 'delete' | 'cancel' | 'publish' | 'upload' | 'assign.role';
    description?: string;
    /**
     * Permission hệ thống (readonly)
     */
    isSystem: boolean;
};

export type PermissionMetaResponseDto = {
    /**
     * Danh sách module hiện có
     */
    modules: Array<string>;
    /**
     * Danh sách action hệ thống (CRUD)
     */
    systemActions: Array<string>;
    /**
     * Danh sách action custom (non-system)
     */
    customActions: Array<string>;
};

export type PermissionPaginatedResponseDto = {
    total: number;
    page: number;
    limit: number;
    data: Array<PermissionResponseDto>;
};

export type UpdatePermissionDto = {
    description?: string;
};

export type CategoryResponseDto = {
    id: string;
    parent_id?: {
        [key: string]: unknown;
    } | null;
    name: string;
    slug: string;
    description?: {
        [key: string]: unknown;
    } | null;
    image?: {
        [key: string]: unknown;
    } | null;
    sortOrder: number;
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
};

export type CategoryPaginatedResponseDto = {
    total: number;
    page: number;
    limit: number;
    data: Array<CategoryResponseDto>;
};

export type CategoryTreeNodeDto = {
    id: string;
    parent_id?: {
        [key: string]: unknown;
    } | null;
    name: string;
    slug: string;
    description?: {
        [key: string]: unknown;
    } | null;
    image?: {
        [key: string]: unknown;
    } | null;
    sortOrder: number;
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
    children?: Array<CategoryTreeNodeDto>;
};

export type AdminCategoryResponseDto = {
    id: string;
    parent_id?: {
        [key: string]: unknown;
    } | null;
    name: string;
    slug: string;
    description?: {
        [key: string]: unknown;
    } | null;
    image?: {
        [key: string]: unknown;
    } | null;
    sortOrder: number;
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
};

export type CreateCategoryDto = {
    /**
     * Category name
     */
    name: string;
    /**
     * SEO slug (auto-generated from name if omitted)
     */
    slug?: string;
    /**
     * Parent category ID
     */
    parent_id?: string;
    description?: string;
    image?: string;
    sortOrder?: number;
    isActive?: boolean;
};

export type UpdateCategoryDto = {
    /**
     * Category name
     */
    name?: string;
    /**
     * SEO slug (auto-generated from name if omitted)
     */
    slug?: string;
    /**
     * Parent category ID
     */
    parent_id?: string;
    description?: string;
    image?: string;
    sortOrder?: number;
    isActive?: boolean;
};

export type UploadResultDto = {
    url: string;
    publicId: string;
    width?: number;
    height?: number;
    format?: string;
    bytes?: number;
    originalName: string;
};

export type MultiUploadResultDto = {
    files: Array<UploadResultDto>;
};

export type ProductListItemDto = {
    id: string;
    category_id: string;
    name: string;
    slug: string;
    basePrice: number;
    sku: string;
    status: 'draft' | 'published' | 'archived';
    isFeatured: boolean;
    createdAt: Date;
    updatedAt: Date;
};

export type ProductPaginatedResponseDto = {
    total: number;
    page: number;
    limit: number;
    data: Array<ProductListItemDto>;
};

export type ProductImageResponseDto = {
    id: string;
    variant_id?: {
        [key: string]: unknown;
    } | null;
    url: string;
    alt?: {
        [key: string]: unknown;
    } | null;
    isPrimary: boolean;
    sortOrder: number;
};

export type ProductVariantResponseDto = {
    id: string;
    name: string;
    sku: string;
    price: number;
    stock: number;
    attributes?: {
        [key: string]: unknown;
    } | null;
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
};

export type TagResponseDto = {
    id: string;
    name: string;
    slug: string;
};

export type ProductResponseDto = {
    id: string;
    category_id: string;
    name: string;
    slug: string;
    description?: {
        [key: string]: unknown;
    } | null;
    basePrice: number;
    sku: string;
    status: 'draft' | 'published' | 'archived';
    isFeatured: boolean;
    images: Array<ProductImageResponseDto>;
    variants: Array<ProductVariantResponseDto>;
    tags: Array<TagResponseDto>;
    createdAt: Date;
    updatedAt: Date;
};

export type AdminProductResponseDto = {
    id: string;
    category_id: string;
    name: string;
    slug: string;
    description?: {
        [key: string]: unknown;
    } | null;
    basePrice: number;
    sku: string;
    status: 'draft' | 'published' | 'archived';
    isFeatured: boolean;
    images: Array<ProductImageResponseDto>;
    variants: Array<ProductVariantResponseDto>;
    tags: Array<TagResponseDto>;
    createdAt: Date;
    updatedAt: Date;
};

export type CreateProductImageDto = {
    url: string;
    variant_id?: string;
    alt?: string;
    isPrimary?: boolean;
    sortOrder?: number;
};

export type CreateProductVariantDto = {
    name: string;
    sku: string;
    price: number;
    stock?: number;
    attributes?: {
        [key: string]: unknown;
    };
    isActive?: boolean;
};

export type CreateProductDto = {
    category_id: string;
    name: string;
    /**
     * Auto-generated from name if omitted
     */
    slug?: string;
    description?: string;
    basePrice: number;
    sku: string;
    status?: 'draft' | 'published' | 'archived';
    isFeatured?: boolean;
    images?: Array<CreateProductImageDto>;
    variants?: Array<CreateProductVariantDto>;
    tagIds?: Array<string>;
};

export type UpdateProductDto = {
    category_id?: string;
    name?: string;
    /**
     * Auto-generated from name if omitted
     */
    slug?: string;
    description?: string;
    basePrice?: number;
    sku?: string;
    status?: 'draft' | 'published' | 'archived';
    isFeatured?: boolean;
    images?: Array<CreateProductImageDto>;
    variants?: Array<CreateProductVariantDto>;
    tagIds?: Array<string>;
};

export type UpdateProductVariantDto = {
    name?: string;
    sku?: string;
    price?: number;
    stock?: number;
    attributes?: {
        [key: string]: unknown;
    };
    isActive?: boolean;
};

export type CreateTagDto = {
    name: string;
    /**
     * Auto-generated from name if omitted
     */
    slug?: string;
};

export type AdminTagResponseDto = {
    id: string;
    name: string;
    slug: string;
};

export type AddressResponseDto = {
    id: string;
    fullName: string;
    phone: string;
    addressLine1: string;
    addressLine2?: {
        [key: string]: unknown;
    };
    city: string;
    province: string;
    country: string;
    postalCode?: {
        [key: string]: unknown;
    };
    isDefault: boolean;
    createdAt: Date;
    updatedAt: Date;
};

export type CreateAddressDto = {
    fullName: string;
    phone: string;
    addressLine1: string;
    addressLine2?: string;
    city: string;
    province: string;
    country?: string;
    postalCode?: string;
    isDefault?: boolean;
};

export type UpdateAddressDto = {
    fullName?: string;
    phone?: string;
    addressLine1?: string;
    addressLine2?: string;
    city?: string;
    province?: string;
    country?: string;
    postalCode?: string;
    isDefault?: boolean;
};

export type CreateOrderItemDto = {
    /**
     * Product variant ID
     */
    variant_id: string;
    quantity: number;
};

export type CreateOrderDto = {
    /**
     * Delivery address ID
     */
    address_id: string;
    items: Array<CreateOrderItemDto>;
    /**
     * Discount coupon code
     */
    discountCode?: string;
    notes?: string;
};

export type OrderItemResponseDto = {
    id: string;
    order_id: string;
    variant_id?: {
        [key: string]: unknown;
    };
    productName: string;
    variantName?: {
        [key: string]: unknown;
    };
    unitPrice: number;
    quantity: number;
    total: number;
};

export type AppliedDiscountDto = {
    id: string;
    code: string;
    type: 'percent' | 'fixed';
    value: number;
};

export type OrderResponseDto = {
    id: string;
    user_id: string;
    address_id?: {
        [key: string]: unknown;
    };
    orderNumber: string;
    status: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'partially_refunded' | 'refunded';
    subtotal: number;
    shippingFee: number;
    discount: number;
    total: number;
    notes?: {
        [key: string]: unknown;
    };
    items: Array<OrderItemResponseDto>;
    discounts: Array<AppliedDiscountDto>;
    createdAt: Date;
    updatedAt: Date;
};

export type CheckoutDto = {
    /**
     * Delivery address ID
     */
    address_id: string;
    /**
     * Discount coupon code
     */
    discountCode?: string;
    notes?: string;
};

export type OrderListItemDto = {
    id: string;
    user_id: string;
    orderNumber: string;
    status: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'partially_refunded' | 'refunded';
    total: number;
    createdAt: Date;
};

export type OrderPaginatedResponseDto = {
    total: number;
    page: number;
    limit: number;
    data: Array<OrderListItemDto>;
};

export type UpdateOrderDto = {
    /**
     * Delivery address ID
     */
    address_id?: string;
    /**
     * Replaces the entire item list
     */
    items?: Array<CreateOrderItemDto>;
    notes?: string;
};

export type OrderStatusHistoryResponseDto = {
    id: string;
    order_id: string;
    fromStatus?: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'partially_refunded' | 'refunded';
    toStatus: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'partially_refunded' | 'refunded';
    changedByType: 'customer' | 'admin' | 'system';
    changedById?: {
        [key: string]: unknown;
    };
    note?: {
        [key: string]: unknown;
    };
    createdAt: Date;
};

export type AdminOrderListItemDto = {
    id: string;
    user_id: string;
    orderNumber: string;
    status: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'partially_refunded' | 'refunded';
    total: number;
    createdAt: Date;
};

export type AdminOrderPaginatedResponseDto = {
    total: number;
    page: number;
    limit: number;
    data: Array<AdminOrderListItemDto>;
};

export type AdminOrderResponseDto = {
    id: string;
    user_id: string;
    address_id?: {
        [key: string]: unknown;
    };
    orderNumber: string;
    status: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'partially_refunded' | 'refunded';
    subtotal: number;
    shippingFee: number;
    discount: number;
    total: number;
    notes?: {
        [key: string]: unknown;
    };
    items: Array<OrderItemResponseDto>;
    discounts: Array<AppliedDiscountDto>;
    createdAt: Date;
    updatedAt: Date;
};

export type UpdateOrderStatusDto = {
    status: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'partially_refunded' | 'refunded';
    /**
     * Reason recorded in the order status history
     */
    note?: string;
};

export type ValidateDiscountDto = {
    code: string;
    /**
     * Order subtotal to calculate discount against
     */
    subtotal: number;
};

export type ValidateDiscountResponseDto = {
    discountId: string;
    code: string;
    type: 'percent' | 'fixed';
    value: number;
    /**
     * Computed discount amount in VND
     */
    discountAmount: number;
};

export type CreateDiscountDto = {
    code: string;
    type: 'percent' | 'fixed';
    /**
     * Percent (0–100) or fixed amount in VND
     */
    value: number;
    /**
     * Minimum subtotal to apply
     */
    minOrderValue?: number;
    /**
     * Max total usages (null = unlimited)
     */
    usageLimit?: number;
    isActive?: boolean;
    startsAt?: Date;
    expiresAt?: Date;
};

export type AdminDiscountResponseDto = {
    id: string;
    code: string;
    type: 'percent' | 'fixed';
    value: number;
    minOrderValue?: {
        [key: string]: unknown;
    };
    usageLimit?: {
        [key: string]: unknown;
    };
    usedCount: number;
    isActive: boolean;
    startsAt?: {
        [key: string]: unknown;
    };
    expiresAt?: {
        [key: string]: unknown;
    };
    createdAt: Date;
    updatedAt: Date;
};

export type AdminDiscountPaginatedResponseDto = {
    total: number;
    page: number;
    limit: number;
    data: Array<AdminDiscountResponseDto>;
};

export type UpdateDiscountDto = {
    code?: string;
    type?: 'percent' | 'fixed';
    /**
     * Percent (0–100) or fixed amount in VND
     */
    value?: number;
    /**
     * Minimum subtotal to apply
     */
    minOrderValue?: number;
    /**
     * Max total usages (null = unlimited)
     */
    usageLimit?: number;
    isActive?: boolean;
    startsAt?: Date;
    expiresAt?: Date;
};

export type CartItemVariantDto = {
    id: string;
    name: string;
    sku: string;
    price: number;
    stock: number;
    attributes?: {
        [key: string]: unknown;
    };
};

export type CartItemResponseDto = {
    id: string;
    cart_id: string;
    variant_id: string;
    variant: CartItemVariantDto;
    quantity: number;
    createdAt: Date;
    updatedAt: Date;
};

export type CartResponseDto = {
    id: string;
    user_id: string;
    items: Array<CartItemResponseDto>;
    createdAt: Date;
    updatedAt: Date;
};

export type AddCartItemDto = {
    variant_id: string;
    quantity?: number;
};

export type UpdateCartItemDto = {
    /**
     * New quantity (min 1)
     */
    quantity: number;
};

export type CreatePaymentDto = {
    /**
     * Order ID to pay for
     */
    order_id: string;
    method: 'cod' | 'vnpay' | 'momo' | 'zalopay' | 'stripe' | 'bank_transfer';
};

export type PaymentResponseDto = {
    id: string;
    order_id: string;
    method: 'cod' | 'vnpay' | 'momo' | 'zalopay' | 'stripe' | 'bank_transfer';
    status: 'pending' | 'completed' | 'failed' | 'partially_refunded' | 'refunded';
    amount: number;
    transactionId?: {
        [key: string]: unknown;
    };
    metadata?: {
        [key: string]: unknown;
    };
    paidAt?: {
        [key: string]: unknown;
    };
    createdAt: Date;
    updatedAt: Date;
};

export type PaymentPaginatedResponseDto = {
    total: number;
    page: number;
    limit: number;
    data: Array<PaymentResponseDto>;
};

export type AdminPaymentResponseDto = {
    id: string;
    order_id: string;
    method: 'cod' | 'vnpay' | 'momo' | 'zalopay' | 'stripe' | 'bank_transfer';
    status: 'pending' | 'completed' | 'failed' | 'partially_refunded' | 'refunded';
    amount: number;
    transactionId?: {
        [key: string]: unknown;
    };
    metadata?: {
        [key: string]: unknown;
    };
    paidAt?: {
        [key: string]: unknown;
    };
    createdAt: Date;
    updatedAt: Date;
};

export type AdminPaymentPaginatedResponseDto = {
    total: number;
    page: number;
    limit: number;
    data: Array<AdminPaymentResponseDto>;
};

export type UpdatePaymentStatusDto = {
    status: 'pending' | 'completed' | 'failed' | 'partially_refunded' | 'refunded';
    transactionId?: string;
    /**
     * Raw response from payment gateway
     */
    metadata?: {
        [key: string]: unknown;
    };
};

export type RefundItemInputDto = {
    /**
     * Order item ID to refund
     */
    order_item_id: string;
    /**
     * Quantity to refund
     */
    quantity: number;
};

export type CreateRefundDto = {
    items: Array<RefundItemInputDto>;
    reason: string;
};

export type RefundItemResponseDto = {
    id: string;
    order_item_id: string;
    quantity: number;
    amount: number;
};

export type RefundResponseDto = {
    id: string;
    payment_id: string;
    order_id: string;
    amount: number;
    reason: string;
    status: 'pending' | 'succeeded' | 'failed';
    transactionId?: {
        [key: string]: unknown;
    };
    actorId?: {
        [key: string]: unknown;
    };
    items: Array<RefundItemResponseDto>;
    createdAt: Date;
};

export type CreateRefundRequestDto = {
    /**
     * Payment ID to refund
     */
    payment_id: string;
    items: Array<RefundItemInputDto>;
    reason: string;
};

export type RefundRequestItemResponseDto = {
    id: string;
    order_item_id: string;
    quantity: number;
    amount: number;
};

export type RefundRequestResponseDto = {
    id: string;
    payment_id: string;
    order_id: string;
    requested_by: string;
    amount: number;
    reason: string;
    status: 'pending' | 'approved' | 'rejected';
    adminNote?: {
        [key: string]: unknown;
    };
    reviewedBy?: {
        [key: string]: unknown;
    };
    reviewedAt?: {
        [key: string]: unknown;
    };
    refund_id?: {
        [key: string]: unknown;
    };
    items: Array<RefundRequestItemResponseDto>;
    createdAt: Date;
};

export type RefundRequestPaginatedResponseDto = {
    total: number;
    page: number;
    limit: number;
    data: Array<RefundRequestResponseDto>;
};

export type ApproveRefundRequestDto = {
    note?: string;
};

export type RejectRefundRequestDto = {
    note: string;
};

export type CreateReviewDto = {
    /**
     * Product to review
     */
    product_id: string;
    rating: number;
    title?: string;
    content?: string;
};

export type ReviewAuthorDto = {
    id: string;
    fullName?: {
        [key: string]: unknown;
    } | null;
    avatar?: {
        [key: string]: unknown;
    } | null;
};

export type ReviewResponseDto = {
    id: string;
    user_id: string;
    user: ReviewAuthorDto;
    product_id: string;
    rating: number;
    title?: {
        [key: string]: unknown;
    } | null;
    content?: {
        [key: string]: unknown;
    } | null;
    isVerified: boolean;
    isApproved: boolean;
    createdAt: Date;
    updatedAt: Date;
};

export type ReviewPaginatedResponseDto = {
    total: number;
    page: number;
    limit: number;
    data: Array<ReviewResponseDto>;
};

export type UpdateReviewDto = {
    rating?: number;
    title?: string;
    content?: string;
};

export type AdminReviewResponseDto = {
    id: string;
    user_id: string;
    user: ReviewAuthorDto;
    product_id: string;
    rating: number;
    title?: {
        [key: string]: unknown;
    } | null;
    content?: {
        [key: string]: unknown;
    } | null;
    isVerified: boolean;
    isApproved: boolean;
    createdAt: Date;
    updatedAt: Date;
};

export type AdminReviewPaginatedResponseDto = {
    total: number;
    page: number;
    limit: number;
    data: Array<AdminReviewResponseDto>;
};

export type WishlistProductDto = {
    id: string;
    name: string;
    slug: string;
    basePrice: number;
    sku: string;
    status: 'draft' | 'published' | 'archived';
    isFeatured: boolean;
    description?: {
        [key: string]: unknown;
    } | null;
};

export type WishlistItemResponseDto = {
    id: string;
    product_id: string;
    product: WishlistProductDto;
    createdAt: Date;
};

export type WishlistResponseDto = {
    items: Array<WishlistItemResponseDto>;
    total: number;
};

export type AddToWishlistDto = {
    /**
     * Product ID to add
     */
    product_id: string;
};

export type BannerResponseDto = {
    id: string;
    title: string;
    subtitle?: {
        [key: string]: unknown;
    };
    position: 'hero' | 'promo_strip' | 'mid_page' | 'popup';
    imageUrl: string;
    imageMobileUrl?: {
        [key: string]: unknown;
    };
    linkType: 'url' | 'product' | 'category' | 'discount';
    linkValue?: {
        [key: string]: unknown;
    };
    sortOrder: number;
    isActive: boolean;
    startsAt?: {
        [key: string]: unknown;
    };
    endsAt?: {
        [key: string]: unknown;
    };
    clickCount: number;
    createdAt: Date;
    updatedAt: Date;
};

export type AdminBannerResponseDto = {
    id: string;
    title: string;
    subtitle?: {
        [key: string]: unknown;
    };
    position: 'hero' | 'promo_strip' | 'mid_page' | 'popup';
    imageUrl: string;
    imageMobileUrl?: {
        [key: string]: unknown;
    };
    linkType: 'url' | 'product' | 'category' | 'discount';
    linkValue?: {
        [key: string]: unknown;
    };
    sortOrder: number;
    isActive: boolean;
    startsAt?: {
        [key: string]: unknown;
    };
    endsAt?: {
        [key: string]: unknown;
    };
    clickCount: number;
    createdAt: Date;
    updatedAt: Date;
};

export type CreateBannerDto = {
    title: string;
    subtitle?: string;
    position: 'hero' | 'promo_strip' | 'mid_page' | 'popup';
    imageUrl: string;
    imageMobileUrl?: string;
    imagePublicId?: string;
    imageMobilePublicId?: string;
    linkType: 'url' | 'product' | 'category' | 'discount';
    linkValue?: string;
    sortOrder?: number;
    isActive?: boolean;
    startsAt?: Date;
    endsAt?: Date;
};

export type BannerOrderItemDto = {
    id: string;
    sortOrder: number;
};

export type ReorderBannersDto = {
    items: Array<BannerOrderItemDto>;
};

export type UpdateBannerDto = {
    title?: string;
    subtitle?: string;
    position?: 'hero' | 'promo_strip' | 'mid_page' | 'popup';
    imageUrl?: string;
    imageMobileUrl?: string;
    imagePublicId?: string;
    imageMobilePublicId?: string;
    linkType?: 'url' | 'product' | 'category' | 'discount';
    linkValue?: string;
    sortOrder?: number;
    isActive?: boolean;
    startsAt?: Date;
    endsAt?: Date;
};

export type AppControllerHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type AppControllerHealthResponses = {
    200: unknown;
};

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthControllerLoginResponses = {
    /**
     * Login successful
     */
    200: TokenResponseDto;
};

export type AuthControllerLoginResponse = AuthControllerLoginResponses[keyof AuthControllerLoginResponses];

export type AuthControllerRegisterData = {
    body: RegisterDto;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type AuthControllerRegisterResponses = {
    /**
     * User registered successfully
     */
    201: MessageResponseDto;
};

export type AuthControllerRegisterResponse = AuthControllerRegisterResponses[keyof AuthControllerRegisterResponses];

export type AuthControllerActiveData = {
    body: ActiveDto;
    path?: never;
    query?: never;
    url: '/auth/active';
};

export type AuthControllerActiveResponses = {
    /**
     * Account activated successfully
     */
    200: UserInformationResponseDto;
};

export type AuthControllerActiveResponse = AuthControllerActiveResponses[keyof AuthControllerActiveResponses];

export type AuthControllerRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type AuthControllerRefreshResponses = {
    /**
     * Token refreshed successfully
     */
    200: TokenResponseDto;
};

export type AuthControllerRefreshResponse = AuthControllerRefreshResponses[keyof AuthControllerRefreshResponses];

export type AuthControllerForgotPasswordData = {
    body: ForgotPasswordDto;
    path?: never;
    query?: never;
    url: '/auth/forgot-password';
};

export type AuthControllerForgotPasswordResponses = {
    /**
     * Password reset email sent if email exists
     */
    200: MessageResponseDto;
};

export type AuthControllerForgotPasswordResponse = AuthControllerForgotPasswordResponses[keyof AuthControllerForgotPasswordResponses];

export type AuthControllerResetPasswordData = {
    body: ResetPasswordDto;
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type AuthControllerResetPasswordResponses = {
    /**
     * Password reset successfully
     */
    200: MessageResponseDto;
};

export type AuthControllerResetPasswordResponse = AuthControllerResetPasswordResponses[keyof AuthControllerResetPasswordResponses];

export type AuthControllerGoogleLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/google';
};

export type AuthControllerGoogleLoginResponses = {
    200: unknown;
};

export type AuthControllerGoogleCallbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/google/callback';
};

export type AuthControllerGoogleCallbackResponses = {
    /**
     * Google login successful
     */
    200: TokenResponseDto;
};

export type AuthControllerGoogleCallbackResponse = AuthControllerGoogleCallbackResponses[keyof AuthControllerGoogleCallbackResponses];

export type UsersControllerGetProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/profile';
};

export type UsersControllerGetProfileResponses = {
    200: UserProfileDto;
};

export type UsersControllerGetProfileResponse = UsersControllerGetProfileResponses[keyof UsersControllerGetProfileResponses];

export type CategoriesControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        /**
         * Filter by category name
         */
        name?: string;
        /**
         * Filter by parent category ID (omit for all, use null for root)
         */
        parent_id?: string;
        /**
         * Filter by active status
         */
        isActive?: boolean;
    };
    url: '/categories';
};

export type CategoriesControllerFindAllResponses = {
    200: CategoryPaginatedResponseDto;
};

export type CategoriesControllerFindAllResponse = CategoriesControllerFindAllResponses[keyof CategoriesControllerFindAllResponses];

export type CategoriesControllerFindTreeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/categories/tree';
};

export type CategoriesControllerFindTreeResponses = {
    200: Array<CategoryTreeNodeDto>;
};

export type CategoriesControllerFindTreeResponse = CategoriesControllerFindTreeResponses[keyof CategoriesControllerFindTreeResponses];

export type CategoriesControllerFindBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/categories/slug/{slug}';
};

export type CategoriesControllerFindBySlugResponses = {
    200: CategoryResponseDto;
};

export type CategoriesControllerFindBySlugResponse = CategoriesControllerFindBySlugResponses[keyof CategoriesControllerFindBySlugResponses];

export type CategoriesControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/categories/{id}';
};

export type CategoriesControllerFindOneResponses = {
    200: CategoryResponseDto;
};

export type CategoriesControllerFindOneResponse = CategoriesControllerFindOneResponses[keyof CategoriesControllerFindOneResponses];

export type ProductsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        /**
         * Filter by product name
         */
        name?: string;
        /**
         * Filter by category ID
         */
        category_id?: string;
        status?: 'draft' | 'published' | 'archived';
        /**
         * Filter featured products
         */
        isFeatured?: boolean;
    };
    url: '/products';
};

export type ProductsControllerFindAllResponses = {
    200: ProductPaginatedResponseDto;
};

export type ProductsControllerFindAllResponse = ProductsControllerFindAllResponses[keyof ProductsControllerFindAllResponses];

export type ProductsControllerFindBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/products/slug/{slug}';
};

export type ProductsControllerFindBySlugResponses = {
    200: ProductResponseDto;
};

export type ProductsControllerFindBySlugResponse = ProductsControllerFindBySlugResponses[keyof ProductsControllerFindBySlugResponses];

export type ProductsControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/products/{id}';
};

export type ProductsControllerFindOneResponses = {
    200: ProductResponseDto;
};

export type ProductsControllerFindOneResponse = ProductsControllerFindOneResponses[keyof ProductsControllerFindOneResponses];

export type TagsControllerFindAllTagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tags';
};

export type TagsControllerFindAllTagsResponses = {
    200: Array<TagResponseDto>;
};

export type TagsControllerFindAllTagsResponse = TagsControllerFindAllTagsResponses[keyof TagsControllerFindAllTagsResponses];

export type TagsControllerFindTagBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/tags/slug/{slug}';
};

export type TagsControllerFindTagBySlugResponses = {
    200: TagResponseDto;
};

export type TagsControllerFindTagBySlugResponse = TagsControllerFindTagBySlugResponses[keyof TagsControllerFindTagBySlugResponses];

export type AddressesControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me/addresses';
};

export type AddressesControllerFindAllResponses = {
    200: Array<AddressResponseDto>;
};

export type AddressesControllerFindAllResponse = AddressesControllerFindAllResponses[keyof AddressesControllerFindAllResponses];

export type AddressesControllerCreateData = {
    body: CreateAddressDto;
    path?: never;
    query?: never;
    url: '/users/me/addresses';
};

export type AddressesControllerCreateResponses = {
    200: AddressResponseDto;
};

export type AddressesControllerCreateResponse = AddressesControllerCreateResponses[keyof AddressesControllerCreateResponses];

export type AddressesControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/me/addresses/{id}';
};

export type AddressesControllerRemoveResponses = {
    /**
     * Address deleted
     */
    204: void;
};

export type AddressesControllerRemoveResponse = AddressesControllerRemoveResponses[keyof AddressesControllerRemoveResponses];

export type AddressesControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/me/addresses/{id}';
};

export type AddressesControllerFindOneResponses = {
    200: AddressResponseDto;
};

export type AddressesControllerFindOneResponse = AddressesControllerFindOneResponses[keyof AddressesControllerFindOneResponses];

export type AddressesControllerUpdateData = {
    body: UpdateAddressDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/me/addresses/{id}';
};

export type AddressesControllerUpdateResponses = {
    200: AddressResponseDto;
};

export type AddressesControllerUpdateResponse = AddressesControllerUpdateResponses[keyof AddressesControllerUpdateResponses];

export type AddressesControllerSetDefaultData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/me/addresses/{id}/default';
};

export type AddressesControllerSetDefaultResponses = {
    200: AddressResponseDto;
};

export type AddressesControllerSetDefaultResponse = AddressesControllerSetDefaultResponses[keyof AddressesControllerSetDefaultResponses];

export type OrdersControllerCreateData = {
    body: CreateOrderDto;
    path?: never;
    query?: never;
    url: '/orders';
};

export type OrdersControllerCreateResponses = {
    201: OrderResponseDto;
};

export type OrdersControllerCreateResponse = OrdersControllerCreateResponses[keyof OrdersControllerCreateResponses];

export type OrdersControllerCheckoutData = {
    body: CheckoutDto;
    path?: never;
    query?: never;
    url: '/orders/checkout';
};

export type OrdersControllerCheckoutResponses = {
    201: OrderResponseDto;
};

export type OrdersControllerCheckoutResponse = OrdersControllerCheckoutResponses[keyof OrdersControllerCheckoutResponses];

export type OrdersControllerFindMineData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        status?: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'partially_refunded' | 'refunded';
        /**
         * Filter by user ID (admin only)
         */
        user_id?: string;
        /**
         * Search by order number (partial match)
         */
        order_number?: string;
        /**
         * Filter orders created on or after this date
         */
        from_date?: string;
        /**
         * Filter orders created on or before this date
         */
        to_date?: string;
        sort_by?: 'createdAt' | 'total' | 'orderNumber';
        sort_order?: 'ASC' | 'DESC';
    };
    url: '/orders/me';
};

export type OrdersControllerFindMineResponses = {
    200: OrderPaginatedResponseDto;
};

export type OrdersControllerFindMineResponse = OrdersControllerFindMineResponses[keyof OrdersControllerFindMineResponses];

export type OrdersControllerFindMineOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/orders/me/{id}';
};

export type OrdersControllerFindMineOneResponses = {
    200: OrderResponseDto;
};

export type OrdersControllerFindMineOneResponse = OrdersControllerFindMineOneResponses[keyof OrdersControllerFindMineOneResponses];

export type OrdersControllerUpdateData = {
    body: UpdateOrderDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/orders/me/{id}';
};

export type OrdersControllerUpdateResponses = {
    200: OrderResponseDto;
};

export type OrdersControllerUpdateResponse = OrdersControllerUpdateResponses[keyof OrdersControllerUpdateResponses];

export type OrdersControllerCancelData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/orders/me/{id}/cancel';
};

export type OrdersControllerCancelResponses = {
    200: OrderResponseDto;
};

export type OrdersControllerCancelResponse = OrdersControllerCancelResponses[keyof OrdersControllerCancelResponses];

export type OrdersControllerGetHistoryData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/orders/me/{id}/history';
};

export type OrdersControllerGetHistoryResponses = {
    200: Array<OrderStatusHistoryResponseDto>;
};

export type OrdersControllerGetHistoryResponse = OrdersControllerGetHistoryResponses[keyof OrdersControllerGetHistoryResponses];

export type DiscountsControllerValidateData = {
    body: ValidateDiscountDto;
    path?: never;
    query?: never;
    url: '/discounts/validate';
};

export type DiscountsControllerValidateResponses = {
    200: ValidateDiscountResponseDto;
};

export type DiscountsControllerValidateResponse = DiscountsControllerValidateResponses[keyof DiscountsControllerValidateResponses];

export type CartsControllerClearCartData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/carts/me';
};

export type CartsControllerClearCartResponses = {
    204: void;
};

export type CartsControllerClearCartResponse = CartsControllerClearCartResponses[keyof CartsControllerClearCartResponses];

export type CartsControllerGetCartData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/carts/me';
};

export type CartsControllerGetCartResponses = {
    200: CartResponseDto;
};

export type CartsControllerGetCartResponse = CartsControllerGetCartResponses[keyof CartsControllerGetCartResponses];

export type CartsControllerAddItemData = {
    body: AddCartItemDto;
    path?: never;
    query?: never;
    url: '/carts/me/items';
};

export type CartsControllerAddItemResponses = {
    200: CartResponseDto;
};

export type CartsControllerAddItemResponse = CartsControllerAddItemResponses[keyof CartsControllerAddItemResponses];

export type CartsControllerRemoveItemData = {
    body?: never;
    path: {
        itemId: string;
    };
    query?: never;
    url: '/carts/me/items/{itemId}';
};

export type CartsControllerRemoveItemResponses = {
    200: CartResponseDto;
};

export type CartsControllerRemoveItemResponse = CartsControllerRemoveItemResponses[keyof CartsControllerRemoveItemResponses];

export type CartsControllerUpdateItemData = {
    body: UpdateCartItemDto;
    path: {
        itemId: string;
    };
    query?: never;
    url: '/carts/me/items/{itemId}';
};

export type CartsControllerUpdateItemResponses = {
    200: CartResponseDto;
};

export type CartsControllerUpdateItemResponse = CartsControllerUpdateItemResponses[keyof CartsControllerUpdateItemResponses];

export type PaymentsControllerCreateData = {
    body: CreatePaymentDto;
    path?: never;
    query?: never;
    url: '/payments';
};

export type PaymentsControllerCreateResponses = {
    201: PaymentResponseDto;
};

export type PaymentsControllerCreateResponse = PaymentsControllerCreateResponses[keyof PaymentsControllerCreateResponses];

export type PaymentsControllerFindMineData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        status?: 'pending' | 'completed' | 'failed' | 'partially_refunded' | 'refunded';
        /**
         * Filter by order (admin)
         */
        order_id?: string;
        /**
         * Filter by user (admin)
         */
        user_id?: string;
    };
    url: '/payments/me';
};

export type PaymentsControllerFindMineResponses = {
    200: PaymentPaginatedResponseDto;
};

export type PaymentsControllerFindMineResponse = PaymentsControllerFindMineResponses[keyof PaymentsControllerFindMineResponses];

export type PaymentsControllerFindMineOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/payments/me/{id}';
};

export type PaymentsControllerFindMineOneResponses = {
    200: PaymentResponseDto;
};

export type PaymentsControllerFindMineOneResponse = PaymentsControllerFindMineOneResponses[keyof PaymentsControllerFindMineOneResponses];

export type RefundRequestsControllerCreateData = {
    body: CreateRefundRequestDto;
    path?: never;
    query?: never;
    url: '/refund-requests';
};

export type RefundRequestsControllerCreateResponses = {
    201: RefundRequestResponseDto;
};

export type RefundRequestsControllerCreateResponse = RefundRequestsControllerCreateResponses[keyof RefundRequestsControllerCreateResponses];

export type RefundRequestsControllerFindMineData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        status?: 'pending' | 'approved' | 'rejected';
        /**
         * Filter by order
         */
        order_id?: string;
        /**
         * Filter by payment
         */
        payment_id?: string;
    };
    url: '/refund-requests/me';
};

export type RefundRequestsControllerFindMineResponses = {
    200: RefundRequestPaginatedResponseDto;
};

export type RefundRequestsControllerFindMineResponse = RefundRequestsControllerFindMineResponses[keyof RefundRequestsControllerFindMineResponses];

export type RefundRequestsControllerFindMineOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/refund-requests/me/{id}';
};

export type RefundRequestsControllerFindMineOneResponses = {
    200: RefundRequestResponseDto;
};

export type RefundRequestsControllerFindMineOneResponse = RefundRequestsControllerFindMineOneResponses[keyof RefundRequestsControllerFindMineOneResponses];

export type ReviewsControllerCreateData = {
    body: CreateReviewDto;
    path?: never;
    query?: never;
    url: '/reviews';
};

export type ReviewsControllerCreateResponses = {
    201: ReviewResponseDto;
};

export type ReviewsControllerCreateResponse = ReviewsControllerCreateResponses[keyof ReviewsControllerCreateResponses];

export type ReviewsControllerFindMyReviewsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        product_id?: string;
        user_id?: string;
        rating?: number;
        isApproved?: boolean;
        isVerified?: boolean;
    };
    url: '/reviews/me';
};

export type ReviewsControllerFindMyReviewsResponses = {
    200: ReviewPaginatedResponseDto;
};

export type ReviewsControllerFindMyReviewsResponse = ReviewsControllerFindMyReviewsResponses[keyof ReviewsControllerFindMyReviewsResponses];

export type ReviewsControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/reviews/{id}';
};

export type ReviewsControllerRemoveResponses = {
    200: unknown;
};

export type ReviewsControllerUpdateData = {
    body: UpdateReviewDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/reviews/{id}';
};

export type ReviewsControllerUpdateResponses = {
    200: ReviewResponseDto;
};

export type ReviewsControllerUpdateResponse = ReviewsControllerUpdateResponses[keyof ReviewsControllerUpdateResponses];

export type ProductReviewsControllerFindApprovedData = {
    body?: never;
    path: {
        productId: string;
    };
    query?: {
        page?: number;
        limit?: number;
        product_id?: string;
        user_id?: string;
        rating?: number;
        isApproved?: boolean;
        isVerified?: boolean;
    };
    url: '/products/{productId}/reviews';
};

export type ProductReviewsControllerFindApprovedResponses = {
    200: ReviewPaginatedResponseDto;
};

export type ProductReviewsControllerFindApprovedResponse = ProductReviewsControllerFindApprovedResponses[keyof ProductReviewsControllerFindApprovedResponses];

export type WishlistsControllerClearWishlistData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/wishlists/me';
};

export type WishlistsControllerClearWishlistResponses = {
    204: void;
};

export type WishlistsControllerClearWishlistResponse = WishlistsControllerClearWishlistResponses[keyof WishlistsControllerClearWishlistResponses];

export type WishlistsControllerGetWishlistData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/wishlists/me';
};

export type WishlistsControllerGetWishlistResponses = {
    200: WishlistResponseDto;
};

export type WishlistsControllerGetWishlistResponse = WishlistsControllerGetWishlistResponses[keyof WishlistsControllerGetWishlistResponses];

export type WishlistsControllerAddProductData = {
    body: AddToWishlistDto;
    path?: never;
    query?: never;
    url: '/wishlists/me';
};

export type WishlistsControllerAddProductResponses = {
    200: WishlistResponseDto;
};

export type WishlistsControllerAddProductResponse = WishlistsControllerAddProductResponses[keyof WishlistsControllerAddProductResponses];

export type WishlistsControllerRemoveProductData = {
    body?: never;
    path: {
        productId: string;
    };
    query?: never;
    url: '/wishlists/me/{productId}';
};

export type WishlistsControllerRemoveProductResponses = {
    200: WishlistResponseDto;
};

export type WishlistsControllerRemoveProductResponse = WishlistsControllerRemoveProductResponses[keyof WishlistsControllerRemoveProductResponses];

export type BannersControllerFindActiveData = {
    body?: never;
    path?: never;
    query?: {
        position?: 'hero' | 'promo_strip' | 'mid_page' | 'popup';
    };
    url: '/banners';
};

export type BannersControllerFindActiveResponses = {
    200: Array<BannerResponseDto>;
};

export type BannersControllerFindActiveResponse = BannersControllerFindActiveResponses[keyof BannersControllerFindActiveResponses];

export type BannersControllerTrackClickData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/banners/{id}/click';
};

export type BannersControllerTrackClickResponses = {
    204: void;
};

export type BannersControllerTrackClickResponse = BannersControllerTrackClickResponses[keyof BannersControllerTrackClickResponses];
